name: Build and Release Unity Project

on:
  push:
    tags:
      - 'v*'
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    name: Build Unity Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repository
      uses: actions/checkout@v2
      with:
        path: 'main-repo'

    - name: Checkout remote Unity project repository
      uses: actions/checkout@v2
      with:
        repository: 'username/unity-project-repo'
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        path: 'unity-project'

    - name: Setup Unity Environment
      uses: game-ci/unity-builder@v2
      with:
        projectPath: unity-project
        unityVersion: '2020.3.0f1'
        targetPlatform: StandaloneWindows64

    - name: Build project
      run: |
        # Example: Adjust the command according to your build configuration
        # This should produce your game executable and any other related files
        cd unity-project
        # Run Unity build command or script

    - name: Archive build output
      run: |
        # Replace `path/to/build/output` with your actual build output directory
        zip -r build.zip path/to/build/output

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: "Release of new version"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build.zip
        asset_name: build.zip
        asset_content_type: application/zip
